import {
    BiSolidDashboard,
    BiSolidUser,
    BiSolidMapPin,
    BiSolidBuilding,
    BiSolidCity,
    BiSolidBriefcase,
    BiSolidCalendarEvent,
    BiSolidNetworkChart,
    BiSolidBullseye,
    BiSolidIdCard,
    BiSolidMessageDetail,
    BiSolidCheckCircle,
    BiSolidRocket,
    BiSolidShieldAlt2,
    BiSolidGroup,
    BiSolidChart,
  } from "react-icons/bi";

  export const menu = [
    { name: "Dashboard", href: "/dashboard", icon: BiSolidDashboard },
    { name: "People", href: "/users", icon: BiSolidUser },
    { name: "Territory", href: "/territory", icon: BiSolidMapPin },
    { name: "Assets", href: "/assets", icon: BiSolidBuilding },
    { name: "Society", href: "/society", icon: BiSolidCity },
    { name: "Desk", href: "/follow-up", icon: BiSolidBriefcase },
    { name: "Event", href: "/event", icon: BiSolidCalendarEvent },
    { name: "Pulse", href: "/pulse", icon: BiSolidChart },
    { name: "Channel Sales", href: "/channel-sales", icon: BiSolidNetworkChart },
    { name: "Campaign", href: "/campaign", icon: BiSolidBullseye },
    { name: "Employee", href: "/employee", icon: BiSolidIdCard },
    { name: "Feddback", href: "/feedback", icon: BiSolidMessageDetail },
    { name: "Task", href: "/task-list", icon: BiSolidCheckCircle },
    { name: "Growth Partner", href: "/growth-partner-list", icon: BiSolidRocket },
    { name: "EHS", href: "/ehs", icon: BiSolidShieldAlt2 },
    { name: "Visitor Management", href: "/visitors", icon: BiSolidIdCard },
    { name: "Community", href: "/community", icon: BiSolidGroup },
  ];

